# Generated by Django 2.2 on 2019-04-17 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190417_2152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
